**Library Imports**

In [68]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

In [69]:
import os
import sys
print(sys.version)   # Python version information

3.4.4 |Anaconda 2.4.0 (64-bit)| (default, Jan 11 2016, 13:54:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


In [70]:
from sympy import *  # Symbolic mathematics
import sympy

In [71]:
import numba        # Decorators for speeding up python functions

In [72]:
#from astropy import constants  # Physical Constants
#from astropy import units      # Physical Units

In [73]:
import matplotlib as mpl  # Standard plotting library
import matplotlib.pyplot as plt 
import seaborn as sns     # Statistical plotting and improved plot style
#import bokeh             # Interactive visualization library

In [74]:
from sympy.utilities.autowrap import ufuncify  # Creates numerical methods 
                                               # from symbolic expressions

In [75]:
from sympy import abc       # Symbolic variables
from sympy import pi as Pi  # Symbolic pi
from sympy import I as I    # Symbolic imaginary unit

**Display**

In [76]:
from IPython.display import display

In [77]:
from IPython.display import set_matplotlib_formats  
set_matplotlib_formats('pdf', 'png')

In [78]:
import ipywidgets

**Settings & Options**

In [79]:
import numpy as np   # N-Dimensional arrays and numerical routines
import scipy         # Numerical routines

np.set_printoptions(precision=5, threshold=100, edgeitems=3, linewidth=75, 
                    suppress=False, nanstr=None, infstr=None, 
                    formatter=None)

In [80]:
import pandas as pd  # Data structures and data analysis tools

pandas_options = {'display.chop_threshold': None,
                  'display.precision': 4,
                  'display.max_columns': 8,
                  'display.max_rows': 8,
                  'display.max_info_columns': 8,
                  'display.max_info_rows': 8}
for key, val in pandas_options.items():
    pd.set_option(key, val)

In [81]:
sympy.interactive.printing.init_printing(use_latex='mathjax')

# Velocity Relative Position to Linear Wall

Agent position $ \mathbf{x} $ velocity $ \mathbf{v} $ and linear wall params $ \mathbf{p}_0 $ and $ \mathbf{p}_1 $

$ \mathbf{q}_0 = \mathbf{p}_0 - \mathbf{x} $

$ \mathbf{q}_1 = \mathbf{p}_1 - \mathbf{x} $

$ \pm \hat{\mathbf{n}} $

$ \mathbf{x} + a \mathbf{v} = \mathbf{p}_0 + b (\mathbf{p}_1 - \mathbf{p}_0), \quad a \in \mathbb{R}^{+},\quad b \in [0, 1] $

$ [\mathbf{v}, -\mathbf{p}] \cdot [a,  b] = \mathbf{q}_0, \quad  \mathbf{p} = \mathbf{p}_1 - \mathbf{p}_0 $

In [82]:
from bokeh.plotting import show, Figure,output_notebook

In [83]:
output_notebook()

Loading BokehJS ...

In [84]:
v = np.random.uniform(-1, 1, 2)

In [85]:
np.arctan2(v[0], v[1])

-2.84447740749

In [86]:
x = np.random.uniform(-1, 1, (3, 2))

In [87]:
np.arctan2(x[:, 0], x[:, 1])

array([-2.77823, -1.64662, -1.48156])

In [88]:
(-np.pi) % (2 * np.pi)

3.141592653589793

In [89]:
np.arange(-2 * pi, 2 * pi, pi / 2)

array([-2*pi, -3*pi/2, -pi, -pi/2, 0, pi/2, pi, 3*pi/2], dtype=object)

In [90]:
_ % (2*pi)

array([0, pi/2, pi, 3*pi/2, 0, pi/2, pi, 3*pi/2], dtype=object)

In [91]:
np.random.uniform(-1, 1, 100)

array([ 0.94893, -0.35126,  0.11796,  0.20146,  0.14913, -0.25969,
       -0.0819 ,  0.50591, -0.66731, -0.74898, -0.72989, -0.2947 ,
       -0.77975,  0.28092,  0.87076,  0.07069, -0.27575, -0.48603,
       -0.96015,  0.60112,  0.40211,  0.02313,  0.14663, -0.50452,
        0.08237, -0.94469, -0.24915, -0.40203,  0.69563,  0.11604,
       -0.99969,  0.56042, -0.83818, -0.59819,  0.39164,  0.24322,
        0.57706, -0.30978,  0.38242,  0.60818, -0.11816,  0.1483 ,
       -0.88207, -0.33485,  0.38059, -0.57644,  0.42989,  0.11792,
       -0.65583,  0.9215 , -0.80875, -0.75938, -0.4104 ,  0.21212,
        0.76502, -0.84117, -0.14707, -0.27956, -0.65233, -0.10096,
        0.20426, -0.43994,  0.10054,  0.89278,  0.72365, -0.6863 ,
       -0.63883,  0.89127, -0.67002, -0.86803,  0.68527,  0.41619,
        0.22658,  0.34519, -0.31802,  0.04147, -0.48835,  0.4344 ,
       -0.1408 , -0.84954,  0.20423, -0.76669,  0.681  , -0.2302 ,
        0.20363, -0.5279 ,  0.9571 , -0.21147,  0.13006,  0.94

In [92]:
np.argmin(_)

30

In [93]:
np.linalg.inv((np.array((1, 2)), np.array((3, 4))))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
np.linalg.inv(np.array(((1, 2), (3, 4))))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [95]:
np.arctan2(0, 0)

0.0

In [105]:
np.array((np.array((1, 1)), np.array((2, 2)))).T

array([[1, 2],
       [1, 2]])